name:CI
on:
  push:
    branches:[master]
  pull_request:
    branches: [ master ]
     

jobs:
    build:
    name: Sign-in test
    runs-on: ubuntu-18.04
    steps:       
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
          
    - name: Angular git hub actions
      uses: actions/angular-github-actions
      
      - name: check the protractor version
        run:  protractor --version

    - name: NPM install dependencies
      run:  npm install
      
           
    - name: Run the config.js
      run:  npm run test
       

#Not required

  # - name: check the protractor version
  #    run:  protractor --version
      
   # - name: Update the webdriver-manager
    #  run:  webdriver-manager update
      
    #- name: Start the selenium server
    #  run:  webdriver-managaer start       
          
          




     
