# This is a basic workflow to help you get started with Actions

name: CI


on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access  
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ env.NODE_VERSION }}
          
    - name: Angular Github Actions
      uses: mayurrawte/github-angular-actions@latest

      # Runs a single command using the runners shell
    - name: NPM install dependencies
      run: npm install protractor -g
      
    - name: Check the version
      run: protractor --version
      
    - name : Update the webdriver
      run :  webdriver-manager update
      
      # Runs a set of commands using the runners shell
    - name: Run the config file 
      run:  protractor config.js
         
